function Hd = LeastSquaresOrder8(stop1,pass1,pass2,stop2)
%LEASTSQUARESORDER8 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 25-Jul-2019 19:07:11

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N      = 8;     % Order
Fstop1 = stop1;  % First Stopband Frequency
Fpass1 = pass1;  % First Passband Frequency
Fpass2 = pass2;  % Second Passband Frequency
Fstop2 = stop2;  % Second Stopband Frequency
Wstop1 = 1;     % First Stopband Weight
Wpass  = 1;     % Passband Weight
Wstop2 = 1;     % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
